export const portfolioCommunityManifest = {
  slug: "portfolio-community",
  name: "Portfolio Community",
  version: 1,
  source: "local-bundle",
  description:
    "Template canonico editorial com hero forte, narrativa enxuta e blocos visuais orientados a portfolio.",
  theme: {
    fontFamily: "Poppins",
    background: "#FBF8CC",
    ink: "#03045E",
    headingSoft: "#F7F197",
    accent: "#F5EE84",
    brown: "#474306",
  },
  assets: {
    cover: "cover.png",
    reference: null,
    notes: "notes.md",
    codeDir: "template-code/template1",
  },
  library: {
    category: "Portfolio",
    tags: ["canonico", "disponivel", "editor-ready"],
    status: "available",
    origin: "Pacote local",
    summary:
      "Portfolio editorial com hero autoral, secoes amplas e leitura visual leve.",
    detail:
      "Pensado para apresentar identidade profissional com imagem forte, narrativa curta, experiencia, projetos selecionados e contato direto sem descaracterizar o template.",
    sortOrder: 0,
  },
  eligibility: {
    requiredProfileFields: ["displayName", "headline", "bio"],
    requiresAvatar: true,
    minExperienceItems: 0,
    minProjectItems: 0,
    minExperienceOrProjectItems: 0,
    minLinkItems: 0,
    minProofItems: 0,
    minLinkOrProofItems: 0,
  },
  resumeDefaults: {
    sections: [
      "summary",
      "behavioral-analysis",
      "education",
      "experience",
      "projects",
      "skills",
      "links",
    ],
    layout: "classic",
    accentColor: "#474306",
    showPhoto: false,
    showLinks: true,
  },
  restrictions: {
    themeLocked: true,
    fontsLocked: true,
    colorsLocked: true,
    identityLocked: true,
    layoutLocked: true,
  },
  blocks: [
    {
      key: "portfolio-hero",
      blockType: "portfolio.hero",
      label: "Hero",
      category: "section",
      version: 1,
      defaultOrder: 0,
      required: true,
      repeatable: false,
      defaultConfig: {
        eyebrow: "Ola, eu sou",
        headline: "Designer de Produto",
        locationLine: "com base na sua cidade.",
        ctaLabel: "Curriculo",
        ctaHref: "/resume",
        showSocialIcons: true,
        showPlusCluster: true,
        showSlashMarks: true,
      },
      editableFields: [
        { key: "eyebrow", label: "Saudacao", element: "text", kind: "text" },
        { key: "headline", label: "Titulo principal", element: "h1", kind: "text" },
        {
          key: "locationLine",
          label: "Linha de localizacao",
          element: "text",
          kind: "text",
        },
        { key: "ctaLabel", label: "CTA", element: "button", kind: "text" },
        { key: "ctaHref", label: "Link do CTA", element: "link", kind: "url" },
        { key: "portrait", label: "Retrato", element: "image", kind: "image" },
        {
          key: "showSocialIcons",
          label: "Icones sociais",
          element: "icon",
          kind: "boolean",
        },
        {
          key: "showPlusCluster",
          label: "Ornamento cruzes",
          element: "icon",
          kind: "boolean",
        },
        {
          key: "showSlashMarks",
          label: "Ornamento barras",
          element: "icon",
          kind: "boolean",
        },
      ],
      assetFields: [
        { key: "portrait", label: "Retrato", element: "image", kind: "image" },
      ],
      allowedChildren: [],
      semanticSlots: [
        {
          slot: "version.headline",
          target: "headline",
          source: "version",
          required: true,
          description: "Headline priorizando customizacao da versao.",
        },
        {
          slot: "profile.avatar",
          target: "portrait",
          source: "profile",
          required: true,
          description: "Imagem principal do hero.",
        },
        {
          slot: "hero.resumeHref",
          target: "ctaHref",
          source: "derived",
          required: true,
          description: "Link publico para o modo curriculo.",
        },
      ],
    },
    {
      key: "portfolio-about",
      blockType: "portfolio.about",
      label: "Sobre",
      category: "section",
      version: 1,
      defaultOrder: 1,
      required: false,
      repeatable: false,
      defaultConfig: {
        title: "sobre.",
      },
      editableFields: [
        { key: "title", label: "Titulo", element: "h2", kind: "text" },
        { key: "body", label: "Texto", element: "text", kind: "longText" },
      ],
      assetFields: [],
      allowedChildren: [],
      semanticSlots: [
        {
          slot: "version.about",
          target: "body",
          source: "version",
          required: true,
          description: "Bio base do usuario com override da versao.",
        },
      ],
    },
    {
      key: "portfolio-education",
      blockType: "portfolio.education",
      label: "Formacao",
      category: "section",
      version: 1,
      defaultOrder: 2,
      required: false,
      repeatable: false,
      defaultConfig: {
        title: "formacao",
      },
      editableFields: [{ key: "title", label: "Titulo", element: "h2", kind: "text" }],
      assetFields: [],
      allowedChildren: [],
      semanticSlots: [
        {
          slot: "education.items",
          target: "items",
          source: "selection",
          required: false,
          description: "Secao que representa cursos, estudos e periodos de formacao.",
        },
      ],
    },
    {
      key: "portfolio-experience",
      blockType: "portfolio.experience",
      label: "Experiencia",
      category: "section",
      version: 1,
      defaultOrder: 3,
      required: false,
      repeatable: false,
      defaultConfig: {
        title: "experiencia",
        maxItems: 3,
      },
      editableFields: [
        { key: "title", label: "Titulo", element: "h2", kind: "text" },
        { key: "maxItems", label: "Maximo de itens", element: "group", kind: "list" },
      ],
      assetFields: [],
      allowedChildren: [],
      semanticSlots: [
        {
          slot: "trajectory.experiences",
          target: "maxItems",
          source: "selection",
          required: false,
          description: "Secao que representa trajetoria profissional.",
        },
      ],
    },
    {
      key: "portfolio-work",
      blockType: "portfolio.work",
      label: "Projetos",
      category: "section",
      version: 1,
      defaultOrder: 4,
      required: false,
      repeatable: true,
      defaultConfig: {
        title: "projetos.",
        intro: "",
        maxItems: 2,
        hiddenProjectIds: [],
        fallbackProjects: [],
      },
      editableFields: [
        { key: "title", label: "Titulo", element: "h2", kind: "text" },
        { key: "intro", label: "Introducao", element: "text", kind: "longText" },
        {
          key: "fallbackProjects",
          label: "Projetos de apoio",
          element: "repeater",
          kind: "list",
        },
      ],
      assetFields: [
        {
          key: "fallbackProjects.image",
          label: "Imagens de apoio",
          element: "image",
          kind: "image",
        },
      ],
      allowedChildren: [],
      semanticSlots: [
        {
          slot: "projects.featured",
          target: "fallbackProjects",
          source: "selection",
          required: false,
          description: "Projetos em destaque da versao.",
        },
      ],
    },
    {
      key: "portfolio-behavioral-analysis",
      blockType: "portfolio.behavioral-analysis",
      label: "Análise comportamental",
      category: "section",
      version: 1,
      defaultOrder: 5,
      required: false,
      repeatable: false,
      defaultConfig: {
        title: "analise comportamental",
      },
      editableFields: [{ key: "title", label: "Titulo", element: "h2", kind: "text" }],
      assetFields: [],
      allowedChildren: [],
      semanticSlots: [
        {
          slot: "vocational.behavioralAnalysis",
          target: "result",
          source: "derived",
          required: false,
          description:
            "Resultado publico do teste vocacional com Big Five, RIASEC e arquetipo.",
        },
      ],
    },
    {
      key: "portfolio-contact",
      blockType: "portfolio.contact",
      label: "Contato",
      category: "section",
      version: 1,
      defaultOrder: 6,
      required: false,
      repeatable: false,
      defaultConfig: {
        title: "contato.",
      },
      editableFields: [
        { key: "title", label: "Titulo", element: "h2", kind: "text" },
        { key: "body", label: "Texto", element: "text", kind: "longText" },
        { key: "image", label: "Imagem", element: "image", kind: "image" },
        { key: "links", label: "Links", element: "repeater", kind: "list" },
      ],
      assetFields: [{ key: "image", label: "Imagem", element: "image", kind: "image" }],
      allowedChildren: [],
      semanticSlots: [
        {
          slot: "contact.links",
          target: "links",
          source: "selection",
          required: false,
          description: "Links e provas publicas resolvidos para contato.",
        },
        {
          slot: "contact.supportImage",
          target: "image",
          source: "derived",
          required: false,
          description: "Imagem de apoio da secao de contato.",
        },
      ],
    },
    {
      key: "portfolio-custom-section",
      blockType: "portfolio.custom-section",
      label: "Secao livre",
      category: "section",
      version: 1,
      defaultOrder: 7,
      required: false,
      repeatable: true,
      defaultConfig: {
        title: "nova secao",
        body: "",
        imageAlign: "center",
        listItems: [],
      },
      editableFields: [
        { key: "title", label: "Titulo", element: "h2", kind: "text" },
        { key: "body", label: "Paragrafo", element: "text", kind: "longText" },
        { key: "image", label: "Imagem", element: "image", kind: "image" },
        {
          key: "imageAlign",
          label: "Alinhamento da imagem",
          element: "group",
          kind: "list",
        },
        { key: "listItems", label: "Lista", element: "repeater", kind: "list" },
      ],
      assetFields: [{ key: "image", label: "Imagem", element: "image", kind: "image" }],
      allowedChildren: [],
      semanticSlots: [],
    },
  ],
} as const;
