ALTER TABLE "Project"
ADD COLUMN IF NOT EXISTS "coverFitMode" TEXT NOT NULL DEFAULT 'crop',
ADD COLUMN IF NOT EXISTS "coverPositionX" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN IF NOT EXISTS "coverPositionY" INTEGER NOT NULL DEFAULT 50;

